### ISSUE TITLE
Import failure: from mdlearn.nn.models.aae.point_3d_aae import AAE3d

### ISSUE THREAD

**Issue by braceal** [ramanathanlab/mdlearn#53]
Unable to import `from mdlearn.nn.models.aae.point_3d_aae import AAE3d`

It looks like the loss module is not included in the pypi distribution. Perhaps because it is missing a __init__.py

```
Python 3.7.9 (default, Aug 31 2020, 13:13:26)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mdlearn
>>> from mdlearn.nn.models.aae.point_3d_aae import AAE3d
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/p/gpfs1/brace3/envs/test-env/lib/python3.7/site-packages/mdlearn/nn/models/aae/point_3d_aae.py", line 8, in <module>
    from mdlearn.nn.models.aae.loss.chamfer_loss import ChamferLoss
ModuleNotFoundError: No module named 'mdlearn.nn.models.aae.loss'
```

**Comment by braceal** [comment]
Addressed in #56
